# Generated by Django 5.2.5 on 2025-09-23 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('ID Card', 'ID Card'), ('Books', 'Books'), ('Clothing', 'Clothing'), ('Other', 'Other')], max_length=50)),
                ('location', models.CharField(help_text='Location where item was lost/found', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images/')),
                ('status', models.CharField(choices=[('Lost', 'Lost'), ('Found', 'Found')], max_length=10)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Approved by admin (for found items)')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
