# Generated by Django 5.2.5 on 2025-09-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0002_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Optional: For easier contact by the campus office.', max_length=15),
        ),
    ]
